name: Playwright E2E Tests

on:
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Selecciona qué pruebas ejecutar'
        required: true
        default: 'all'
        type: choice
        options:
        - all
        - login
        - registro
        - cuentas
        - navegacion
        - transferencias

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Instalar dependencias del sistema
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-venv
        
    - name: Crear entorno virtual Python
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        
    - name: Instalar dependencias Python
      run: |
        source .venv/bin/activate
        pip install -r requirements.txt
        
    - name: Instalar Playwright browsers
      run: |
        source .venv/bin/activate
        playwright install
        playwright install-deps
        
    - name: Instalar dependencias Node.js
      run: npm install
      
    - name: Instalar dependencias del backend
      run: |
        cd redux-athena-bank/backend
        npm install
        
    - name: Instalar dependencias del frontend
      run: |
        cd redux-athena-bank/frontend
        npm install
        
    - name: Levantar aplicación (backend y frontend)
      run: |
        npm run start:app &
        sleep 10
        
    - name: Esperar que la aplicación esté lista
      run: npm run wait-for-app
      
    - name: Ejecutar pruebas
      run: |
        case "${{ github.event.inputs.test_suite }}" in
          "login")
            npm run test:login
            ;;
          "registro")
            npm run test:registro
            ;;
          "cuentas")
            npm run test:cuentas
            ;;
          "navegacion")
            npm run test:navegacion
            ;;
          "transferencias")
            npm run test:transferencias
            ;;
          *)
            npm run test:all
            ;;
        esac
        
    - name: Generar reporte Allure
      if: always()
      run: |
        npm install -g allure-commandline
        allure generate allure-results --clean -o allure-report
        
    - name: Subir resultados de pruebas
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results/
        
    - name: Subir reporte Allure
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
